### ISSUE TITLE
Does it works in epsilon 18.2.3?

### ISSUE THREAD

**Issue by LoucaFrss** [numworks/epsilon-sample-app-rust#10]
I don't really understand, since epsilon 16, (with n110) the epsilon is supposed to be locked but we can unlock it with Phi. In epsilon 18.2.3 we can't anymore so can we add apps to the numworks even if it is locked?

**Comment by adriweb** [comment]
There were just [some commits](https://github.com/numworks/epsilon-sample-app-cpp/commits/master) added to the C++ sample repo, so it would indicate that app support isn't dead :)
